### ISSUE TITLE
Error 7.8.1 shown despite valid `iati-organisation/@default-currency`

### ISSUE THREAD

**Issue by andylolz** [data4development/IATI-data-validator#43]
**Describe the bug**

I’m seeing Error 7.8.1:

> The Value must have a specified Currency, or the Activity must have a default Currency.

…for an org file that includes a valid `iati-organisation/@default-currency`.

**To Reproduce**

1. [Go here](https://test-validator.iatistandard.org/view/dqf/files/3cdd529d7d02589e5156e79d95ad666f)
2. See error:
    > The Value must have a specified Currency, or the Activity must have a default Currency.
3. Note that [the dataset in question](https://iatiregistry.org/dataset/pwyf-org) is an org file, and has a valid `iati-organisation/@default-currency`

**Expected behavior**
This error shouldn’t be displayed when all `iati-organisation/@default-currency`s are present are correct.

**Screenshots**
![Screenshot 2019-11-13 at 09 28 21](https://user-images.githubusercontent.com/464193/68750552-f6914d00-05f7-11ea-8653-bb7d7c7fc954.png)

**Additional context**
The suspected cause of this bug is outlined in data4development/IATI-Rulesets#59

**Comment by rolfkleef** [comment]
@andylolz we indeed need to fix this test, it's looking for iati-activity/@default-currency

**Comment by rolfkleef** [comment]
[Fixed in IATI-Rulesets](https://github.com/data4development/IATI-Rulesets/commit/d9606a358c6184edd2e2c19380762d1e8f080a88), to be deployed still.

**Comment by andylolz** [comment]
Great – thanks.

Would it be possible to bump this ticket when it’s deployed, so I can test? (Testing at the moment appears to show the bug is still there.)

**Comment by rolfkleef** [comment]
here's a ping @andylolz - the "check data" runs the latest version, the reports of existing public data will be updated when they are refreshed (github automation already closed the ticket I see)

**Comment by andylolz** [comment]
Ah okay, gotcha – I see. Thanks for elucidating.

> the reports of existing public data will be updated when they are refreshed

When does that happen? Is it possible for me to queue or trigger it?

I see the record of when it last happened here, but not when it is scheduled to next happen:
https://test-validator.iatistandard.org/organisation/pwyf

**Comment by rolfkleef** [comment]
Right now files are reprocessed after 48 hours (adding a trigger to reprocess when the ruleset version changes is in the backlog). Depending on the workload on the cluster it can take a while for all files to be processed (there are currently max 15 parallel machines in the test environment).

**Comment by andylolz** [comment]
Cool – thanks for clarifying Rolf!
